(ns shimmers.test-namespaces
  (:require
   ;; namespaces to test
   [shimmers.algorithm.line-clipping-test]
   [shimmers.algorithm.lines-test]
   [shimmers.algorithm.minimum-spanning-tree-test]
   [shimmers.algorithm.mosaic-test]
   [shimmers.algorithm.quadtree-test]
   [shimmers.algorithm.rtree-test]
   [shimmers.algorithm.space-colonization-test]
   [shimmers.algorithm.square-packing-test]
   [shimmers.algorithm.polygon-detection-test]
   [shimmers.algorithm.wave-function-collapse-test]
   [shimmers.automata.memory-test]
   [shimmers.automata.simplify-test]
   [shimmers.common.sequence-test]
   [shimmers.common.svg-test]
   [shimmers.math.core-test]
   [shimmers.math.geometry-test]
   [shimmers.math.geometry.collisions-test]
   [shimmers.math.geometry.ellipse-test]
   [shimmers.math.geometry.group-test]
   [shimmers.math.geometry.intersection-test]
   [shimmers.math.geometry.line-test]
   [shimmers.math.geometry.triangle-test]
   [shimmers.math.graph-test]
   [shimmers.math.hexagon-test]))
